# Quality Data Analyst Test

## Data Analysis of Uisce Ã‰ireann (Irish Water) Customer Survey Data

### **Name**: Kaustubh Keni

# Introduction

Welcome to the analysis of the Irish Water Customer Survey Data. This project aims to preprocess and analyze the survey responses to uncover valuable insights about customer satisfaction and service quality.

### Objectives:

* **Data Preprocessing**: Cleaning and preparing the data for analysis.
* **Exploratory Data Analysis (EDA)**: Understanding the data through summary statistics and visualizations.
* **Insights Extraction**: Identifying key patterns and insights from the data.

### Dataset:

The dataset consists of responses from customers of Irish Water. Each row represents a unique respondent, and the columns contain various survey questions and demographic information.

### Tools:

* **Python**: The primary programming language used for this analysis.
* **Pandas**: For data manipulation and analysis.
* **NumPy**: For numerical operations.
* **Matplotlib/Seaborn**: For data visualization.
* **Jupyter Notebook**: For documenting the analysis process interactively.

Let's dive into the data preprocessing and analysis to derive meaningful insights from the customer survey responses.

In [1]:
# Importing necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Reading the excel file

df = pd.read_excel("K:\QDA Test\QDA Dataset\CX Data.xlsx")

In [7]:
# Display first 10 rows of the dataset

df.head(10)

,responseid,Invite Date,Callback request,Survey Date,PersonID,WorkorderID,CaseID,CC_ID,SRNumber,Journey,...,Next steps clearly explained,Query resolution,Satisfaction with Engineer,Listened to and understood,Next steps were explained,Kept informed,Resolution time frame,Agents' ability,Resolution time for query,How could contact centre deal better?
0,102568,2024-06-25 17:39:52,NaN,6/30/2024,6669680897,27090747.0,NaN,NaN,8.114740e+09,Operations Fieldwork,...,10 - Extremely Satisfied,10 - Extremely Satisfied,10 - Extremely Satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,102567,2024-06-28 14:46:39,Yes,6/29/2024,6139482334,27114400.0,NaN,NaN,8.461674e+08,Operations Fieldwork,...,5,1 - Extremely Dissatisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It isn't the Contact Centre. It is the fact th...
2,102566,2024-06-19 14:16:49,Yes,6/29/2024,9275995403,28123353.0,NaN,NaN,1.725808e+09,Operations Fieldwork,...,3,1 - Extremely Dissatisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Actually come out and fix the issue
3,102565,2024-06-28 14:46:39,NaN,6/28/2024,4030850147,28773440.0,NaN,NaN,8.787918e+09,Operations Fieldwork,...,9,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,102564,2024-06-28 14:46:39,NaN,6/28/2024,7114907659,29072355.0,NaN,NaN,5.076597e+09,Operations Fieldwork,...,9,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,102562,2024-06-28 14:46:39,NaN,6/28/2024,2245759551,29078422.0,NaN,NaN,5.371413e+09,Operations Fieldwork,...,9,8,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,102561,2024-06-28 14:46:39,No,6/28/2024,2039131000,29078947.0,NaN,NaN,3.892111e+09,Operations Fieldwork,...,10 - Extremely Satisfied,10 - Extremely Satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,102560,2024-06-28 14:46:39,NaN,6/28/2024,3330140270,29076717.0,NaN,NaN,3.012042e+09,Operations Fieldwork,...,10 - Extremely Satisfied,10 - Extremely Satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,102558,2024-06-28 14:46:39,Yes,6/28/2024,2968037929,27051055.0,NaN,NaN,1.154582e+09,Operations Fieldwork,...,1 - Extremely Dissatisfied,1 - Extremely Dissatisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,102554,2024-06-28 14:46:39,NaN,6/28/2024,7681580725,27078630.0,NaN,NaN,7.777290e+09,Operations Fieldwork,...,6,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Get the shape of Dataframe

df.shape

(838, 35)

In [9]:
# For finding the list of columns in the data

df.columns

Index(['responseid', 'Invite Date', 'Callback request', 'Survey Date',
       'PersonID', 'WorkorderID', 'CaseID', 'CC_ID', 'SRNumber', 'Journey',
       'Customer Channel', 'Customer Class', 'Case type', 'LocalAuthority',
       'Case Characteristic', 'Customer Query', 'Resolution',
       'Resolution Code', 'Reasons for resolution outcome',
       'Overall satisfaction', 'Reasons for overall satisfaction score',
       'Easy', 'Single word', 'Suggestions for improvement',
       'Satisfaction with contact centre experience',
       'Next steps clearly explained', 'Query resolution',
       'Satisfaction with Engineer', 'Listened to and understood',
       'Next steps were explained', 'Kept informed', 'Resolution time frame',
       'Agents' ability', 'Resolution time for query',
       'How could contact centre deal better?'],
      dtype='object')

In [10]:
# Finding data types

df.dtypes

responseid                                              int64
Invite Date                                    datetime64[ns]
Callback request                                       object
Survey Date                                            object
PersonID                                                int64
WorkorderID                                           float64
CaseID                                                float64
CC_ID                                                 float64
SRNumber                                              float64
Journey                                                object
Customer Channel                                       object
Customer Class                                         object
Case type                                             float64
LocalAuthority                                         object
Case Characteristic                                    object
Customer Query                                         object
Resolution                                             object
Resolution Code                                        object
Reasons for resolution outcome                         object
Overall satisfaction                                   object
Reasons for overall satisfaction score                 object
Easy                                                   object
Single word                                           float64
Suggestions for improvement                            object
Satisfaction with contact centre experience            object
Next steps clearly explained                           object
Query resolution                                       object
Satisfaction with Engineer                             object
Listened to and understood                            float64
Next steps were explained                             float64
Kept informed                                         float64
Resolution time frame                                 float64
Agents' ability                                        object
Resolution time for query                              object
How could contact centre deal better?                  object
dtype: object

In [11]:
# To the unique values in the dataset
# In order to determine which columns are categorical and which are continuous

df.nunique()

responseid                                     838
Invite Date                                     15
Callback request                                 2
Survey Date                                     42
PersonID                                       838
WorkorderID                                    604
CaseID                                           0
CC_ID                                          234
SRNumber                                       604
Journey                                          2
Customer Channel                                 1
Customer Class                                   2
Case type                                        0
LocalAuthority                                  34
Case Characteristic                             15
Customer Query                                   7
Resolution                                       3
Resolution Code                                 22
Reasons for resolution outcome                 705
Overall satisfaction                            10
Reasons for overall satisfaction score         761
Easy                                             7
Single word                                      0
Suggestions for improvement                    642
Satisfaction with contact centre experience     10
Next steps clearly explained                    10
Query resolution                                10
Satisfaction with Engineer                      10
Listened to and understood                       0
Next steps were explained                        0
Kept informed                                    0
Resolution time frame                            0
Agents' ability                                 10
Resolution time for query                       10
How could contact centre deal better?          134
dtype: int64

In [13]:
# Columns to be dropped

columns_to_drop = ['responseid', 'Invite Date', 'Callback request',
       'CaseID', 'Case type', 'Resolution Code', 'Reasons for resolution outcome',
       'Reasons for overall satisfaction score',
       'Single word', 'Suggestions for improvement', 'Listened to and understood',
       'Next steps were explained', 'Kept informed', 'Resolution time frame',
       'How could contact centre deal better?']

# Drop specified columns

df.drop(columns = columns_to_drop, inplace = True)

#Verify columns dropped

df.head(5)

,Survey Date,PersonID,WorkorderID,CC_ID,SRNumber,Journey,Customer Channel,Customer Class,LocalAuthority,Case Characteristic,Customer Query,Resolution,Overall satisfaction,Easy,Satisfaction with contact centre experience,Next steps clearly explained,Query resolution,Satisfaction with Engineer,Agents' ability,Resolution time for query
0,6/30/2024,6669680897,27090747.0,NaN,8.114740e+09,Operations Fieldwork,Telephone,DOM,CORK COUNTY,Carry out part replacement repair of <=32mm MD...,You recently contacted Uisce Ã‰ireann/Irish Wat...,"YES, it was ^f(""Intropipe"").any('4') ? ""comple...",10 - Extremely Satisfied,7 - Extremely Easy,10 - Extremely Satisfied,10 - Extremely Satisfied,10 - Extremely Satisfied,10 - Extremely Satisfied,NaN,NaN
1,6/29/2024,6139482334,27114400.0,NaN,8.461674e+08,Operations Fieldwork,Telephone,DOM,CORK COUNTY,Waste Action - Unblock Sewer - Below Ground Wa...,You recently contacted Uisce Ã‰ireann/Irish Wat...,"NO, it has still not been ^f(""Intropipe"").any(...",1 - Extremely Dissatisfied,1 - Extremely Difficult,4,5,1 - Extremely Dissatisfied,NaN,NaN,NaN
2,6/29/2024,9275995403,28123353.0,NaN,1.725808e+09,Operations Fieldwork,Telephone,DOM,DUBLIN SOUTH COUNTY,Investigation No Water - Below Ground Drinking...,You recently contacted Uisce Ã‰ireann/Irish Wat...,"NO, it has still not been ^f(""Intropipe"").any(...",1 - Extremely Dissatisfied,1 - Extremely Difficult,5,3,1 - Extremely Dissatisfied,NaN,NaN,NaN
3,6/28/2024,4030850147,28773440.0,NaN,8.787918e+09,Operations Fieldwork,Telephone,DOM,NORTH TIPPERARY COUNTY,Investigation Blockage - Below Ground Waste Water,You recently contacted Uisce Ã‰ireann/Irish Wat...,"YES, it was ^f(""Intropipe"").any('4') ? ""comple...",9,7 - Extremely Easy,9,9,9,NaN,NaN,NaN
4,6/28/2024,7114907659,29072355.0,NaN,5.076597e+09,Operations Fieldwork,Telephone,DOM,CORK CITY,Investigation Blockage - Below Ground Waste Water,You recently contacted Uisce Ã‰ireann/Irish Wat...,"YES, it was ^f(""Intropipe"").any('4') ? ""comple...",8,6,9,9,9,NaN,NaN,NaN

In [16]:
# Duplicate the column Resolution

df['Resolution Feedback'] = df['Resolution']

# Verify new duplicate column added

df.head(5)

,Survey Date,PersonID,WorkorderID,CC_ID,SRNumber,Journey,Customer Channel,Customer Class,LocalAuthority,Case Characteristic,...,Resolution,Overall satisfaction,Easy,Satisfaction with contact centre experience,Next steps clearly explained,Query resolution,Satisfaction with Engineer,Agents' ability,Resolution time for query,Resolution Feedback
0,6/30/2024,6669680897,27090747.0,NaN,8.114740e+09,Operations Fieldwork,Telephone,DOM,CORK COUNTY,Carry out part replacement repair of <=32mm MD...,...,"YES, it was ^f(""Intropipe"").any('4') ? ""comple...",10 - Extremely Satisfied,7 - Extremely Easy,10 - Extremely Satisfied,10 - Extremely Satisfied,10 - Extremely Satisfied,10 - Extremely Satisfied,NaN,NaN,"YES, it was ^f(""Intropipe"").any('4') ? ""comple..."
1,6/29/2024,6139482334,27114400.0,NaN,8.461674e+08,Operations Fieldwork,Telephone,DOM,CORK COUNTY,Waste Action - Unblock Sewer - Below Ground Wa...,...,"NO, it has still not been ^f(""Intropipe"").any(...",1 - Extremely Dissatisfied,1 - Extremely Difficult,4,5,1 - Extremely Dissatisfied,NaN,NaN,NaN,"NO, it has still not been ^f(""Intropipe"").any(..."
2,6/29/2024,9275995403,28123353.0,NaN,1.725808e+09,Operations Fieldwork,Telephone,DOM,DUBLIN SOUTH COUNTY,Investigation No Water - Below Ground Drinking...,...,"NO, it has still not been ^f(""Intropipe"").any(...",1 - Extremely Dissatisfied,1 - Extremely Difficult,5,3,1 - Extremely Dissatisfied,NaN,NaN,NaN,"NO, it has still not been ^f(""Intropipe"").any(..."
3,6/28/2024,4030850147,28773440.0,NaN,8.787918e+09,Operations Fieldwork,Telephone,DOM,NORTH TIPPERARY COUNTY,Investigation Blockage - Below Ground Waste Water,...,"YES, it was ^f(""Intropipe"").any('4') ? ""comple...",9,7 - Extremely Easy,9,9,9,NaN,NaN,NaN,"YES, it was ^f(""Intropipe"").any('4') ? ""comple..."
4,6/28/2024,7114907659,29072355.0,NaN,5.076597e+09,Operations Fieldwork,Telephone,DOM,CORK CITY,Investigation Blockage - Below Ground Waste Water,...,"YES, it was ^f(""Intropipe"").any('4') ? ""comple...",8,6,9,9,9,NaN,NaN,NaN,"YES, it was ^f(""Intropipe"").any('4') ? ""comple..."

In [38]:
# Replace values to simplify

# Defining the replacements

replacements_j = { 'Operations Fieldwork' : 'Operations',
                   'Commercial - Billing Query' : 'Commercial'
                 }


replacements_cc = { 'Carry out part replacement repair of <=32mm MDPE potable water service pipe' : 'Part replacement repair',
                    'Waste Action - Unblock Sewer - Below Ground Waste Water' : 'Unblock Sewer',
                    'Investigation No Water - Below Ground Drinking Water' : 'No Water',
                    'Investigation Blockage - Below Ground Waste Water' : 'Blockage',
                    'Repair Main - Below Ground Drinking Water' : 'Repair Mains',
                    'Investigation Visible Leak - Below Ground Drinking Water' : 'Visible Leak'
                  }


replacements_cq = { 'You recently contacted Uisce Ã‰ireann/Irish Water to change something on your account' : 'Change of Account Details',
                   'You recently contacted Uisce Ã‰ireann/Irish Water to make a card payment' : 'Card Payment',
                   'You recently contacted Uisce Ã‰ireann/Irish Water with a query on a blockage' : 'Blockage',
                   'You recently contacted Uisce Ã‰ireann/Irish Water with a query on a leakage' : 'Leakage',
                   'You recently contacted Uisce Ã‰ireann/Irish Water with a query on no water' : 'No Water',
                   'You recently contacted Uisce Ã‰ireann/Irish Water with a query on payment' : 'Payment Query',
                   'You recently contacted Uisce Ã‰ireann/Irish Water with an account balance request' : 'Account Balance Request'
                 }


replacements_r = { "YES, it was ^f(\"Intropipe\").any('4') ? \"completed\": \"resolved\"^ to my satisfaction": 'Yes',
                   "YES, it was ^f(\"Intropipe\").any('4') ? \"completed\": \"resolved\"^ but not to my satisfaction": 'Yes',
                   "NO, it has still not been ^f(\"Intropipe\").any('4') ? \"completed\": \"resolved\"^/still ongoing": 'No'
                 }


replacements_rf = { "YES, it was ^f(\"Intropipe\").any('4') ? \"completed\": \"resolved\"^ to my satisfaction": 'Satisfied',
                    "YES, it was ^f(\"Intropipe\").any('4') ? \"completed\": \"resolved\"^ but not to my satisfaction": 'Not Satisfied',
                    "NO, it has still not been ^f(\"Intropipe\").any('4') ? \"completed\": \"resolved\"^/still ongoing": 'Still Ongoing'
                  }


replacements_os = { '10 - Extremely Satisfied' : 10,
                   '1 - Extremely Dissatisfied' : 1
                 }


replacements_e = { '7 - Extremely Easy' : 7,
                  '1 - Extremely Difficult' : 1
                }


# Replace in the Case Characteristic column

df['Journey'] = df['Journey'].replace(replacements_j)

df['Case Characteristic'] = df['Case Characteristic'].replace(replacements_cc)

df['Customer Query'] = df['Customer Query'].replace(replacements_cq)

df['Resolution'] = df['Resolution'].replace(replacements_r)

df['Resolution Feedback'] = df['Resolution Feedback'].replace(replacements_rf)

df['Overall satisfaction'] = df['Overall satisfaction'].replace(replacements_os)

df['Easy'] = df['Easy'].replace(replacements_e)

df['Satisfaction with contact centre experience'] = df['Satisfaction with contact centre experience'].replace(replacements_os)

df['Next steps clearly explained'] = df['Next steps clearly explained'].replace(replacements_os)

df['Query resolution'] = df['Query resolution'].replace(replacements_os)

df['Satisfaction with Engineer'] = df['Satisfaction with Engineer'].replace(replacements_os)

df["Agents' ability"] = df["Agents' ability"].replace(replacements_os)

df['Resolution time for query'] = df['Resolution time for query'].replace(replacements_os)


# Verify the replacements have been made

print(df[['Case Characteristic', 'Customer Query',  'Resolution', 'Resolution Feedback', 'Overall satisfaction',
          'Easy','Journey', 'Satisfaction with contact centre experience', 'Next steps clearly explained', 
          'Query resolution', 'Satisfaction with Engineer', "Agents' ability", 'Resolution time for query']].head(5))

       Case Characteristic Customer Query Resolution Resolution Feedback  \
0  Part replacement repair        Leakage        Yes           Satisfied
1            Unblock Sewer       Blockage         No       Still Ongoing
2                 No Water       No Water         No       Still Ongoing
3                 Blockage       Blockage        Yes           Satisfied
4                 Blockage       Blockage        Yes           Satisfied

   Overall satisfaction  Easy     Journey  \
0                    10     7  Operations
1                     1     1  Operations
2                     1     1  Operations
3                     9     7  Operations
4                     8     6  Operations

  Satisfaction with contact centre experience Next steps clearly explained  \
0                                          10                           10
1                                           4                            5
2                                           5                            3
3                                           9                            9
4                                           9                            9

  Query resolution Satisfaction with Engineer Agents' ability  \
0               10                         10             NaN
1                1                        NaN             NaN
2                1                        NaN             NaN
3                9                        NaN             NaN
4                9                        NaN             NaN

  Resolution time for query
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN

In [39]:
# Dropping few more columns, Columns to be dropped

additional_columns_to_drop = ['PersonID', 'WorkorderID', 'CC_ID', 'SRNumber' ]

# Drop specified columns

df.drop(columns = additional_columns_to_drop, inplace = True)

#Verify columns dropped

df.head(5)

,Survey Date,Journey,Customer Channel,Customer Class,LocalAuthority,Case Characteristic,Customer Query,Resolution,Overall satisfaction,Easy,Satisfaction with contact centre experience,Next steps clearly explained,Query resolution,Satisfaction with Engineer,Agents' ability,Resolution time for query,Resolution Feedback
0,2024-06-30,Operations,Telephone,DOM,CORK COUNTY,Part replacement repair,Leakage,Yes,10,7,10,10,10,10,NaN,NaN,Satisfied
1,2024-06-29,Operations,Telephone,DOM,CORK COUNTY,Unblock Sewer,Blockage,No,1,1,4,5,1,NaN,NaN,NaN,Still Ongoing
2,2024-06-29,Operations,Telephone,DOM,DUBLIN SOUTH COUNTY,No Water,No Water,No,1,1,5,3,1,NaN,NaN,NaN,Still Ongoing
3,2024-06-28,Operations,Telephone,DOM,NORTH TIPPERARY COUNTY,Blockage,Blockage,Yes,9,7,9,9,9,NaN,NaN,NaN,Satisfied
4,2024-06-28,Operations,Telephone,DOM,CORK CITY,Blockage,Blockage,Yes,8,6,9,9,9,NaN,NaN,NaN,Satisfied

In [34]:
# Looking at the null values 

df.isnull().sum()

Survey Date                                      0
Journey                                          0
Customer Channel                                 0
Customer Class                                   0
LocalAuthority                                   0
Case Characteristic                              0
Customer Query                                   0
Resolution                                       0
Overall satisfaction                             0
Easy                                             0
Satisfaction with contact centre experience    234
Next steps clearly explained                   234
Query resolution                               234
Satisfaction with Engineer                     615
Agents' ability                                604
Resolution time for query                      604
Resolution Feedback                              0
dtype: int64

In [56]:
# Convert required datatypes

df['Satisfaction with contact centre experience'] = df['Satisfaction with contact centre experience'].astype(float)

df['Next steps clearly explained'] = df['Next steps clearly explained'].astype(float)

df['Query resolution'] = df['Query resolution'].astype(float)

df['Satisfaction with Engineer'] = df['Satisfaction with Engineer'].astype(float)

df["Agents' ability"] = df["Agents' ability"].astype(float)

df['Resolution time for query'] = df['Resolution time for query'].astype(float)

# Adjust rating for 'Easy' column from 1 to 10 for easier comparision
# Convert 'Easy' column to float to ensure division works correctly
df['Easy'] = df['Easy'].astype(float)

# Scale the 'Easy' column from range [1, 7] to [1, 10]
df['Easy'] = ((df['Easy'] - 1) / (7 - 1)) * (10 - 1) + 1

# Convert the scaled values to integers (if desired)
df['Easy'] = df['Easy'].round().astype(int)

# Verify the changes

df.head(5)

,Survey Date,Journey,Customer Channel,Customer Class,LocalAuthority,Case Characteristic,Customer Query,Resolution,Overall satisfaction,Easy,Satisfaction with contact centre experience,Next steps clearly explained,Query resolution,Satisfaction with Engineer,Agents' ability,Resolution time for query,Resolution Feedback
0,2024-06-30,Operations,Telephone,DOM,CORK COUNTY,Part replacement repair,Leakage,Yes,10,10,10.0,10.0,10.0,10.0,NaN,NaN,Satisfied
1,2024-06-29,Operations,Telephone,DOM,CORK COUNTY,Unblock Sewer,Blockage,No,1,1,4.0,5.0,1.0,NaN,NaN,NaN,Still Ongoing
2,2024-06-29,Operations,Telephone,DOM,DUBLIN SOUTH COUNTY,No Water,No Water,No,1,1,5.0,3.0,1.0,NaN,NaN,NaN,Still Ongoing
3,2024-06-28,Operations,Telephone,DOM,NORTH TIPPERARY COUNTY,Blockage,Blockage,Yes,9,10,9.0,9.0,9.0,NaN,NaN,NaN,Satisfied
4,2024-06-28,Operations,Telephone,DOM,CORK CITY,Blockage,Blockage,Yes,8,8,9.0,9.0,9.0,NaN,NaN,NaN,Satisfied

In [59]:
df.dtypes

Survey Date                                    datetime64[ns]
Journey                                                object
Customer Channel                                       object
Customer Class                                         object
LocalAuthority                                         object
Case Characteristic                                    object
Customer Query                                         object
Resolution                                             object
Overall satisfaction                                    int32
Easy                                                    int32
Satisfaction with contact centre experience           float64
Next steps clearly explained                          float64
Query resolution                                      float64
Satisfaction with Engineer                            float64
Agents' ability                                       float64
Resolution time for query                             float64
Resolution Feedback                                    object
dtype: object